### ISSUE TITLE
Support older python versions

### ISSUE THREAD

**Issue by 100rab-S** [todofixthis/class-registry#19]
Hi @todofixthis,
Thank you for providing a convenient and useful package. I was wondering if it is compatible with older versions of Python. It would be great if it could run on versions up to 3.8.

**Comment by todofixthis** [comment]
Kia ora @100rab-S. Thanks for reaching out! I'm glad to hear that ClassRegistry is useful for you 😺 I'm only one person supporting this and other projects in my spare time, so to keep things manageable for me I can only commit to supporting the three most recent versions of Python.

The current version of ClassRegistry has some syntax that is not compatible with Python 3.9 or earlier, however the functionality of the library hasn't changed significantly since [v3.0.5](https://github.com/todofixthis/class-registry/releases/tag/3.0.5) which does work with Python 3.8.

**Comment by 100rab-S** [comment]
Thanks @todofixthis. I'll try out the said version. I'm using just the auto-register and the simple registry functionality. Hope these works as same as the latest version.
